# Generated by Django 5.1.1 on 2024-10-05 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('name', models.CharField(db_column='tx_name', max_length=70)),
                ('age', models.IntegerField(db_column='nb_age')),
                ('rg', models.CharField(db_column='tx_rg', max_length=12)),
                ('cpf', models.CharField(db_column='tx_cpf', max_length=12)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('name', models.CharField(db_column='tx_name', max_length=70)),
                ('registration', models.CharField(db_column='tx_registration', max_length=15)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('description', models.CharField(db_column='tx_description')),
                ('quantity', models.IntegerField(db_column='nb_quantity', default=0)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('nrf', models.CharField(db_column='tx_sale', max_length=255)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.PROTECT, to='teste.client')),
                ('id_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.PROTECT, to='teste.employee')),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.PROTECT, to='teste.product')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
